// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generate_attributes_cpp
NumericMatrix generate_attributes_cpp(int n, int m, double lambda);
RcppExport SEXP _masc_generate_attributes_cpp(SEXP nSEXP, SEXP mSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_attributes_cpp(n, m, lambda));
    return rcpp_result_gen;
END_RCPP
}
// rMASC_sampling_cpp
List rMASC_sampling_cpp(const arma::mat& trial_x, const arma::vec& w, double sigma, double alpha, double delta, double theta, double lambda, int max_steps, int n_options, int n_attributes);
RcppExport SEXP _masc_rMASC_sampling_cpp(SEXP trial_xSEXP, SEXP wSEXP, SEXP sigmaSEXP, SEXP alphaSEXP, SEXP deltaSEXP, SEXP thetaSEXP, SEXP lambdaSEXP, SEXP max_stepsSEXP, SEXP n_optionsSEXP, SEXP n_attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type trial_x(trial_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_steps(max_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type n_options(n_optionsSEXP);
    Rcpp::traits::input_parameter< int >::type n_attributes(n_attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(rMASC_sampling_cpp(trial_x, w, sigma, alpha, delta, theta, lambda, max_steps, n_options, n_attributes));
    return rcpp_result_gen;
END_RCPP
}
// MASC_SearchRule_myopic_cpp
NumericVector MASC_SearchRule_myopic_cpp(int n, int m, NumericVector w, NumericVector w2, NumericVector sp, double thresh, double alpha, NumericMatrix prec, NumericMatrix mu);
RcppExport SEXP _masc_MASC_SearchRule_myopic_cpp(SEXP nSEXP, SEXP mSEXP, SEXP wSEXP, SEXP w2SEXP, SEXP spSEXP, SEXP threshSEXP, SEXP alphaSEXP, SEXP precSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sp(spSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type prec(precSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(MASC_SearchRule_myopic_cpp(n, m, w, w2, sp, thresh, alpha, prec, mu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_masc_generate_attributes_cpp", (DL_FUNC) &_masc_generate_attributes_cpp, 3},
    {"_masc_rMASC_sampling_cpp", (DL_FUNC) &_masc_rMASC_sampling_cpp, 10},
    {"_masc_MASC_SearchRule_myopic_cpp", (DL_FUNC) &_masc_MASC_SearchRule_myopic_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_masc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
