# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MASC_SearchRule_myopic_cpp <- function(n, m, w, w2, sp, thresh, alpha, prec, mu) {
    .Call(`_masc_MASC_SearchRule_myopic_cpp`, n, m, w, w2, sp, thresh, alpha, prec, mu)
}

generate_attributes_cpp <- function(n, m, lambda) {
    .Call(`_masc_generate_attributes_cpp`, n, m, lambda)
}

rMASC_sampling_cpp <- function(trial_x, w, sigma, alpha, delta, theta, lambda, max_steps, n_options, n_attributes) {
    .Call(`_masc_rMASC_sampling_cpp`, trial_x, w, sigma, alpha, delta, theta, lambda, max_steps, n_options, n_attributes)
}

